name: Deploy to Dokku

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: webfactory/ssh-agent@v0.5.1
      with:
        ssh-private-key: ${{ secrets.DOKKU_KEY }}
    - name: Deploy to Dokku
      run: |
        ssh-keyscan -H 22 "dokku-dev.hekaton.studio" >> ~/.ssh/known_hosts
        ssh dokku@dokku-dev.hekaton.studio "config:set --no-restart roller-bot DISCORD_TOKEN='${{ secrets.DISCORD_TOKEN }}'
        git-push dokku@dokku-dev.hekaton.studio:roller-bot"
