name: Deploy to Dokku

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{ secrets.DOKKU_KEY }}
      PROJECT_NAME: roller-bot
    steps:
    - uses: actions/checkout@v2
    - uses: webfactory/ssh-agent@v0.5.1
    - name: Deploy to Dokku
      run: |
        ssh-keyscan -H 22 "dokku-dev.hekaton.studio" >> ~/.ssh/known_hosts
        ssh dokku@dokku-dev.hekaton.studio "config:set --no-restart ${{ env.PROJECT_NAME }} DISCORD_TOKEN='${{ secrets.DISCORD_TOKEN }}'
        git-push dokku@dokku-dev.hekaton.studio:${{ env.PROJECT_NAME }}"
