name: Deploy to Dokku

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Dokku
      shell: bash
      env:
        DOKKU_KEY: ${{ secrets.DOKKU_KEY }}
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        PROJECT_NAME: roller-bot
      run: |
        ssh-add - <<< "${{ env.DOKKU_KEY }}" > /dev/null
        ssh-keyscan -H 22 "dokku-dev.hekaton.studio" >> ~/.ssh/known_hosts
        ssh dokku@dokku-dev.hekaton.studio "config:set --no-restart ${{ env.PROJECT_NAME }} DISCORD_TOKEN='${{ env.DISCORD_TOKEN }}'"
        git-push dokku@dokku-dev.hekaton.studio:${{ env.PROJECT_NAME }}
