name: Deploy to Dokku

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: deploy
        name: Deploy to dokku
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
            ssh-private-key: ${{ secrets.DOKKU_KEY }}
            dokku-host: 'dokku-dev.hekaton.studio'
            app-name: 'roller-bot'
