name: Deploy to Dokku

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Dokku
      shell: bash
      env:
        DISCORD_TOKEN: "${{ secrets.DISCORD_TOKEN }}"
        DOKKU_KEY: |
          ${{ secrets.DOKKU_KEY }}
        PROJECT_NAME: roller-bot
      run: |
        ssh-add - <<< "$DOKKU_KEY" > /dev/null
        ssh-keyscan -H 22 "dokku-dev.hekaton.studio" >> ~/.ssh/known_hosts
        ssh dokku@dokku-dev.hekaton.studio "config:set --no-restart $PROJECT_NAME DISCORD_TOKEN='$DISCORD_TOKEN'"
        git-push dokku@dokku-dev.hekaton.studio:${PROJECT_NAME}
